spring:
  profiles: default
  application:
    name: schedule-api-batch-processing
  data:
    mongodb:
      host: localhost
      port: 27017
      database: Indian-Railways
logging:
  level:
    root: INFO
server:
  port: 9091